# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  flutter: circleci/flutter@2.0.1
  android: circleci/android@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-ios:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    macos:
      xcode: "14.2.0"
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.7.6
      - run:
          name: "Build release ios"
          command: "flutter build ios --release"
  build-android:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.0.3
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - run:
          name: "Build release android"
          command: "flutter build apk --release"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  builds:
    jobs:
      - build-ios
      - build-android
